version: 2.0.{build}

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}' 
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Debug

image: Visual Studio 2019

before_build:
  - nuget restore
  
build:
  project: SharpDHCPServer.sln

test: off

artifacts:
  - path: '**\DotNetProjects.DhcpServer*.nupkg'
  
#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: 88aMSx9ONm6ZEyZHiWughpXbF3QGPuYy7yjQxQSt69pDc89aKMBYm8KPOaCIUX9s
  artifact: /.*\.nupkg/
  
  
  
